# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Council < Formula
  desc "AI Council Orchestrator — run multiple AI agent CLIs in parallel for planning & critique consensus."
  homepage "https://github.com/alijamal14/council"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alijamal14/council/releases/download/v1.2.1/council_darwin_x86_64.tar.gz"
      sha256 "74ed97fdfbba5c6663f4d85e2bd0f36f6f751cfd66889e3a41436f4744c049dc"

      define_method(:install) do
        bin.install "council"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alijamal14/council/releases/download/v1.2.1/council_darwin_aarch64.tar.gz"
      sha256 "8b3e29d8f55691f3969e24702e6553acd85abccc81b5ecb24368c14126b7105c"

      define_method(:install) do
        bin.install "council"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alijamal14/council/releases/download/v1.2.1/council_linux_x86_64.tar.gz"
      sha256 "c8661ee76c5ac1353c4d298315b826d9ab23b38b452ad45450ca2504c663ef13"
      define_method(:install) do
        bin.install "council"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alijamal14/council/releases/download/v1.2.1/council_linux_aarch64.tar.gz"
      sha256 "ba9daf8411013e0507b81ac1216eea11a495893eb7c7c7291afcdb2b95c10792"
      define_method(:install) do
        bin.install "council"
      end
    end
  end

  test do
    system "#{bin}/council", "--version"
  end
end
