# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Council < Formula
  desc "AI Council Orchestrator — run multiple AI agent CLIs in parallel for planning & critique consensus."
  homepage "https://github.com/alijamal14/council"
  version "1.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alijamal14/council/releases/download/v1.1.2/council_darwin_x86_64.tar.gz"
      sha256 "44635771ba1d312017a35ca285ea4537059d72031ae9748fa3ddefab0e372196"

      define_method(:install) do
        bin.install "council"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alijamal14/council/releases/download/v1.1.2/council_darwin_aarch64.tar.gz"
      sha256 "5e954146ea96ecf201c15bb7f851b1ffbd9de86dbbd1af1586395c6db92f1e9b"

      define_method(:install) do
        bin.install "council"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alijamal14/council/releases/download/v1.1.2/council_linux_x86_64.tar.gz"
      sha256 "bd0cfe7b7c9c116cbbe5b37d9d2dc1e72f2701ca6f8fec0c43ceeea9c88a2387"
      define_method(:install) do
        bin.install "council"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alijamal14/council/releases/download/v1.1.2/council_linux_aarch64.tar.gz"
      sha256 "72c1bd2d347764f8727213e06024f63b74ef33fcd1e78f75438962f308c42be0"
      define_method(:install) do
        bin.install "council"
      end
    end
  end

  test do
    system "#{bin}/council", "--version"
  end
end
